### ISSUE TITLE
How about using `Relaxed` when increase the counter

### ISSUE THREAD

**Issue by mapleFU** [ganler/OptimizedThreadSafeRefCounting#1]
> Typical use for relaxed memory ordering is incrementing counters, such as the reference counters of std::shared_ptr, since this only requires atomicity, but not ordering or synchronization (note that decrementing the shared_ptr counters requires acquire-release synchronization with the destructor)

The part is mentioned in CppReference, how about using `Relaxed`?

**Comment by ganler** [comment]
A big thank for reminding me about this. I've already modified my code.
Thx again.
